if __name__ == "__main__":
    print('     /~\\')
    print('    ( oo|')
    print('    _\\=/_')
    print('   /  _  \\')
    print('  //|/.\\|\\\\')
    print(' ||  \\ /  ||')
    print('============')
    print('|          |')
    print('|          |')
    print('|          |')
